In [1]:
## On Not being able to use python for Despina's. She said in L10 that the only thing she wants to see is that we've done it and that it wont be marked.
## Only assessed on whether it works or not

import pandas as pd
import numpy as np

import seaborn as sns
import matplotlib.pyplot as plt

from scipy.stats import norm
from datetime import datetime, time 

## Importing hand-made modules
import sys
scraper_modules_path = 'C:/Users/ABour/Desktop/Energy Systems & Data Analytics/Modules/Energy Analysis - Aidan/Smart Meters/custom_modules'
if scraper_modules_path not in sys.path:
    sys.path.append(scraper_modules_path)

import pre_processing as pp
import feature_gen as fg

<br>

### Reading in and time series feature generation

In [41]:
df_smart_meters_wide = pd.read_csv('data/consumption_d.csv', parse_dates=['GMT'])
df_smart_meters_wide

,GMT,D0000,D0001,D0002,D0003,D0004,D0005,D0006,D0007,D0008,...,D1015,D1016,D1017,D1018,D1019,D1020,D1021,D1022,D1023,D1024
0,2011-11-23 09:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2011-11-23 09:30:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2011-11-23 10:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2011-11-23 10:30:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2011-11-23 11:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2011-11-23 11:30:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2011-11-23 12:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2011-11-23 12:30:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2011-11-23 13:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2011-11-23 13:30:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2011-11-23 14:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,2011-11-23 14:30:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,2011-11-23 15:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,2011-11-23 15:30:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,2011-11-23 16:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,2011-11-23 16:30:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,2011-11-23 17:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,2011-11-23 17:30:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,2011-11-23 18:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,2011-11-23 18:30:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,2011-11-23 19:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,2011-11-23 19:30:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,2011-11-23 20:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,2011-11-23 20:30:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,2011-11-23 21:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,2011-11-23 21:30:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,2011-11-23 22:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,2011-11-23 22:30:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,2011-11-23 23:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,2011-11-23 23:30:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39697,2014-02-27 09:30:00,0.060,0.134,0.139,0.031,0.068,0.118,0.178,0.151,0.041,...,0.139,0.014,0.229,0.049,0.199,0.099,0.069,0.040,0.010,0.072
39698,2014-02-27 10:00:00,0.034,0.117,0.135,0.005,0.295,0.153,0.128,0.101,0.068,...,0.151,0.013,0.204,0.055,0.441,0.161,0.064,0.046,0.015,0.056
39699,2014-02-27 10:30:00,0.069,0.154,0.115,0.042,0.370,0.134,0.105,0.084,0.071,...,0.034,0.033,0.126,0.071,0.186,0.151,0.033,0.074,0.070,0.051
39700,2014-02-27 11:00:00,0.035,0.034,0.327,0.141,0.431,0.176,0.154,0.283,0.043,...,0.054,0.132,0.149,0.046,0.160,0.106,0.050,0.082,0.042,0.080
39701,2014-02-27 11:30:00,0.056,0.104,0.467,0.089,0.048,0.252,0.146,0.200,0.120,...,0.041,0.013,0.290,0.059,0.136,0.100,0.082,0.066,0.029,0.048
39702,2014-02-27 12:00:00,0.262,0.040,0.489,0.060,0.063,0.123,0.127,0.216,0.082,...,0.020,0.006,0.135,0.070,0.082,0.174,0.034,0.238,0.550,0.030
39703,2014-02-27 12:30:00,0.114,0.035,0.136,0.223,0.065,0.149,0.154,0.296,0.048,...,0.028,0.006,0.101,0.038,0.163,0.185,0.060,0.067,0.037,0.055
39704,2014-02-27 13:00:00,0.147,0.041,0.117,0.053,0.176,0.125,0.191,2.246,0.081,...,0.060,0.014,0.124,0.066,0.054,0.160,0.104,0.081,0.073,0.080
39705,2014-02-27 13:30:00,0.034,0.030,0.170,0.052,0.150,0.115,0.059,0.231,0.080,...,0.017,0.046,0.188,0.063,0.094,0.165,0.083,0.075,0.071,0.019
39706,2014-02-27 14:00:00,0.174,0.041,0.151,0.051,0.078,0.164,0.019,0.202,0.125,...,0.039,0.157,0.145,0.039,0.089,0.121,0.068,0.059,0.026,0.020
39707,2014-02-27 14:30:00,0.136,0.033,0.250,0.052,0.117,0.161,0.029,0.133,0.123,...,0.016,0.014,0.162,0.072,0.091,0.121,0.034,0.043,0.009,0.051
39708,2014-02-27 15:00:00,0.151,0.062,0.220,0.051,0.162,0.180,0.268,0.114,0.094,...,0.104,0.013,0.143,0.048,0.100,0.132,0.078,0.026,0.023,0.035
39709,2014-02-27 15:30:00,0.131,0.055,0.115,0.194,0.076,0.154,0.320,0.188,0.148,...,0.048,0.015,0.367,0.056,0.090,0.136,0.055,0.042,0.035,0.051
39710,2014-02-27 16:00:00,0.283,0.050,0.110,0.458,0.148,0.136,0.512,0.133,0.189,...,0.110,0.034,0.254,0.067,0.093,0.108,0.034,0.364,0.029,0.039
39711,2014-02-27 16:30:00,0.221,0.097,1.391,0.228,0.169,0.154,0.497,0.139,0.094,...,0.113,0.117,0.143,0.035,0.090,0.045,0.062,0.581,0.012,0.055
39712,2014-02-27 17:00:00,0.167,0.120,0.673,0.086,0.239,0.154,0.755,0.116,0.134,...,0.096,0.014,0.155,0.074,0.090,0.063,0.071,0.621,0.021,0.354
39713,2014-02-27 17:30:00,0.171,0.094,1.171,0.086,0.237,0.219,0.423,0.141,0.113,...,0.187,0.013,0.134,0.044,0.175,0.481,0.036,0.609,0.008,0.103
39714,2014-02-27 18:00:00,0.243,0.098,1.959,0.093,0.350,0.241,0.499,0.228,0.162,...,0.095,0.020,0.150,0.066,0.162,1.010,0.064,0.185,0.057,0.068
39715,2014-02-27 18:30:00,0.290,0.083,0.845,0.086,0.369,0.190,0.422,0.148,0.277,...,0.172,0.001,0.199,0.107,0.337,0.827,0.089,0.331,0.088,0.041
39716,2014-02-27 19:00:00,0.305,0.058,1.247,0.048,0.281,0.215,0.868,0.199,0.316,...,0.174,0.034,0.165,0.076,0.252,0.657,0.087,0.285,0.082,0.096
39717,2014-02-27 19:30:00,0.307,0.066,2.084,0.058,0.361,0.238,1.265,0.178,0.338,...,0.207,0.019,0.157,0.079,0.259,0.258,0.067,0.176,0.081,0.105
39718,2014-02-27 20:00:00,0.322,0.061,1.511,0.100,0.271,0.186,0.749,0.136,0.815,...,0.266,0.020,0.136,0.055,0.224,0.282,0.048,0.190,0.231,0.075
39719,2014-02-27 20:30:00,0.173,0.042,0.610,0.097,0.240,0.226,0.258,0.160,0.337,...,0.067,0.135,0.138,0.053,0.201,0.278,0.291,0.200,0.104,0.288
39720,2014-02-27 21:00:00,0.212,0.036,0.536,0.096,0.200,0.239,0.287,0.185,0.561,...,0.116,0.020,0.159,0.096,0.274,0.263,0.223,0.155,0.097,0.107
39721,2014-02-27 21:30:00,0.178,0.037,0.404,0.096,0.218,0.186,0.458,0.177,0.916,...,0.073,0.043,0.222,0.074,0.390,0.270,0.102,0.168,0.094,0.129
39722,2014-02-27 22:00:00,0.401,0.046,0.457,0.095,0.203,0.232,0.284,0.126,0.528,...,0.089,0.031,0.139,0.085,0.393,0.324,0.127,0.151,0.071,0.123
39723,2014-02-27 22:30:00,0.190,0.184,0.430,0.096,0.176,0.240,0.310,0.126,0.650,...,0.033,0.020,0.132,0.085,0.388,0.268,0.114,0.179,0.059,0.109
39724,2014-02-27 23:00:00,0.119,0.108,0.309,0.087,0.098,0.195,0.236,0.161,0.182,...,0.048,0.021,0.104,0.037,0.312,0.244,0.088,0.222,0.063,0.096
39725,2014-02-27 23:30:00,0.042,0.097,0.353,0.052,0.020,0.225,0.344,0.164,0.077,...,0.037,0.020,0.093,0.067,0.208,0.296,0.083,0.212,0.051,0.252
39726,2014-02-28 00:00:00,0.056,0.070,0.289,0.052,0.017,0.304,0.331,0.125,0.066,...,0.019,0.020,0.138,0.273,0.120,0.263,0.060,0.192,0.049,0.072

In [48]:
df_smart_meters_long = (pd.wide_to_long(df_smart_meters_wide, stubnames='D', i='GMT', j='id')
                        .reset_index()
                        .rename(columns={'D':'kWh', 'GMT':'datetime'})
                        .dropna()
                            )

df_smart_meters_long.head(10)

                     GMT  id    kWh
8644 2012-05-21 11:00:00   0  0.081
8645 2012-05-21 11:30:00   0  0.035
8646 2012-05-21 12:00:00   0  0.037
8647 2012-05-21 12:30:00   0  0.072
8648 2012-05-21 13:00:00   0  0.329
8649 2012-05-21 13:30:00   0  0.127
8650 2012-05-21 14:00:00   0  0.203
8651 2012-05-21 14:30:00   0  0.037
8652 2012-05-21 15:00:00   0  0.068
8653 2012-05-21 15:30:00   0  0.037

In [53]:
df_smart_meters = df_smart_meters_long.copy()

In [52]:
#df_smart_meters = df_smart_meters.drop(columns='stdorToU').copy()

std_bool = df_smart_meters.datetime.dt.year!=2013
df_smart_meters_std = df_smart_meters.copy()[std_bool]
df_smart_meters_ToU = df_smart_meters.copy()[~std_bool]

df_smart_meters_ToU

                    datetime    id    kWh
19422    2013-01-01 00:00:00     0  1.043
19423    2013-01-01 00:30:00     0  0.404
19424    2013-01-01 01:00:00     0  0.185
19425    2013-01-01 01:30:00     0  0.151
19426    2013-01-01 02:00:00     0  0.139
19427    2013-01-01 02:30:00     0  0.105
19428    2013-01-01 03:00:00     0  0.122
19429    2013-01-01 03:30:00     0  0.091
19430    2013-01-01 04:00:00     0  0.110
19431    2013-01-01 04:30:00     0  0.100
19432    2013-01-01 05:00:00     0  0.091
19433    2013-01-01 05:30:00     0  0.107
19434    2013-01-01 06:00:00     0  0.084
19435    2013-01-01 06:30:00     0  0.118
19436    2013-01-01 07:00:00     0  0.086
19437    2013-01-01 07:30:00     0  0.081
19438    2013-01-01 08:00:00     0  0.054
19439    2013-01-01 08:30:00     0  0.306
19440    2013-01-01 09:00:00     0  0.105
19441    2013-01-01 09:30:00     0  0.073
19442    2013-01-01 10:00:00     0  0.105
19443    2013-01-01 10:30:00     0  0.097
19444    2013-01-01 11:00:00     0  0.084
19445    2013-01-01 11:30:00     0  0.104
19446    2013-01-01 12:00:00     0  0.066
19447    2013-01-01 12:30:00     0  0.088
19448    2013-01-01 13:00:00     0  0.209
19449    2013-01-01 13:30:00     0  0.220
19450    2013-01-01 14:00:00     0  0.248
19451    2013-01-01 14:30:00     0  0.246
...                      ...   ...    ...
40717360 2013-12-31 09:00:00  1024  0.054
40717361 2013-12-31 09:30:00  1024  0.104
40717362 2013-12-31 10:00:00  1024  0.064
40717363 2013-12-31 10:30:00  1024  0.060
40717364 2013-12-31 11:00:00  1024  0.095
40717365 2013-12-31 11:30:00  1024  0.055
40717366 2013-12-31 12:00:00  1024  0.084
40717367 2013-12-31 12:30:00  1024  0.061
40717368 2013-12-31 13:00:00  1024  0.081
40717369 2013-12-31 13:30:00  1024  0.076
40717370 2013-12-31 14:00:00  1024  0.088
40717371 2013-12-31 14:30:00  1024  0.121
40717372 2013-12-31 15:00:00  1024  0.063
40717373 2013-12-31 15:30:00  1024  0.057
40717374 2013-12-31 16:00:00  1024  0.195
40717375 2013-12-31 16:30:00  1024  0.190
40717376 2013-12-31 17:00:00  1024  0.218
40717377 2013-12-31 17:30:00  1024  0.197
40717378 2013-12-31 18:00:00  1024  0.195
40717379 2013-12-31 18:30:00  1024  0.243
40717380 2013-12-31 19:00:00  1024  0.230
40717381 2013-12-31 19:30:00  1024  0.242
40717382 2013-12-31 20:00:00  1024  1.004
40717383 2013-12-31 20:30:00  1024  0.211
40717384 2013-12-31 21:00:00  1024  0.142
40717385 2013-12-31 21:30:00  1024  0.076
40717386 2013-12-31 22:00:00  1024  0.100
40717387 2013-12-31 22:30:00  1024  0.098
40717388 2013-12-31 23:00:00  1024  0.089
40717389 2013-12-31 23:30:00  1024  0.093

[17851428 rows x 3 columns]

In [54]:
print(f'ToU Size: {df_smart_meters_ToU.shape[0]}')
print(f'Std Size: {df_smart_meters_std.shape[0]}')

ToU Size: 17851428
Std Size: 13798086

In [55]:
df_smart_meters_ToU = df_smart_meters_ToU[df_smart_meters_ToU.datetime!=datetime(2013, 1, 1, 0, 0)] # Drop 1st HH of 2013
df_smart_meters_ToU

                    datetime    id    kWh
19423    2013-01-01 00:30:00     0  0.404
19424    2013-01-01 01:00:00     0  0.185
19425    2013-01-01 01:30:00     0  0.151
19426    2013-01-01 02:00:00     0  0.139
19427    2013-01-01 02:30:00     0  0.105
19428    2013-01-01 03:00:00     0  0.122
19429    2013-01-01 03:30:00     0  0.091
19430    2013-01-01 04:00:00     0  0.110
19431    2013-01-01 04:30:00     0  0.100
19432    2013-01-01 05:00:00     0  0.091
19433    2013-01-01 05:30:00     0  0.107
19434    2013-01-01 06:00:00     0  0.084
19435    2013-01-01 06:30:00     0  0.118
19436    2013-01-01 07:00:00     0  0.086
19437    2013-01-01 07:30:00     0  0.081
19438    2013-01-01 08:00:00     0  0.054
19439    2013-01-01 08:30:00     0  0.306
19440    2013-01-01 09:00:00     0  0.105
19441    2013-01-01 09:30:00     0  0.073
19442    2013-01-01 10:00:00     0  0.105
19443    2013-01-01 10:30:00     0  0.097
19444    2013-01-01 11:00:00     0  0.084
19445    2013-01-01 11:30:00     0  0.104
19446    2013-01-01 12:00:00     0  0.066
19447    2013-01-01 12:30:00     0  0.088
19448    2013-01-01 13:00:00     0  0.209
19449    2013-01-01 13:30:00     0  0.220
19450    2013-01-01 14:00:00     0  0.248
19451    2013-01-01 14:30:00     0  0.246
19452    2013-01-01 15:00:00     0  0.155
...                      ...   ...    ...
40717360 2013-12-31 09:00:00  1024  0.054
40717361 2013-12-31 09:30:00  1024  0.104
40717362 2013-12-31 10:00:00  1024  0.064
40717363 2013-12-31 10:30:00  1024  0.060
40717364 2013-12-31 11:00:00  1024  0.095
40717365 2013-12-31 11:30:00  1024  0.055
40717366 2013-12-31 12:00:00  1024  0.084
40717367 2013-12-31 12:30:00  1024  0.061
40717368 2013-12-31 13:00:00  1024  0.081
40717369 2013-12-31 13:30:00  1024  0.076
40717370 2013-12-31 14:00:00  1024  0.088
40717371 2013-12-31 14:30:00  1024  0.121
40717372 2013-12-31 15:00:00  1024  0.063
40717373 2013-12-31 15:30:00  1024  0.057
40717374 2013-12-31 16:00:00  1024  0.195
40717375 2013-12-31 16:30:00  1024  0.190
40717376 2013-12-31 17:00:00  1024  0.218
40717377 2013-12-31 17:30:00  1024  0.197
40717378 2013-12-31 18:00:00  1024  0.195
40717379 2013-12-31 18:30:00  1024  0.243
40717380 2013-12-31 19:00:00  1024  0.230
40717381 2013-12-31 19:30:00  1024  0.242
40717382 2013-12-31 20:00:00  1024  1.004
40717383 2013-12-31 20:30:00  1024  0.211
40717384 2013-12-31 21:00:00  1024  0.142
40717385 2013-12-31 21:30:00  1024  0.076
40717386 2013-12-31 22:00:00  1024  0.100
40717387 2013-12-31 22:30:00  1024  0.098
40717388 2013-12-31 23:00:00  1024  0.089
40717389 2013-12-31 23:30:00  1024  0.093

[17850404 rows x 3 columns]

In [56]:
## Reading in ToU price data
df_ToU_price_raw = pd.read_csv('data/tariff_d.csv', parse_dates=['GMT']).rename({'GMT':'datetime', 'Price':'price', 'Event_tags':'event'}, axis=1)

## Cleaning and extracting price 
def clean_and_extract_price(df_ToU_price):
    df_ToU_price = df_ToU_price[df_ToU_price.datetime.dt.year==2013] # Dropping spare day at start of 2014
    df_ToU_price = df_ToU_price.drop(columns=['event']).set_index('datetime') # Drop unnecessary columns, set datetime as index
    return df_ToU_price

df_price = clean_and_extract_price(df_ToU_price_raw.copy())
df_price = pd.Series(df_price.price)
df_price

datetime
2013-01-01 00:30:00    0.1176
2013-01-01 01:00:00    0.1176
2013-01-01 01:30:00    0.1176
2013-01-01 02:00:00    0.1176
2013-01-01 02:30:00    0.1176
2013-01-01 03:00:00    0.1176
2013-01-01 03:30:00    0.1176
2013-01-01 04:00:00    0.1176
2013-01-01 04:30:00    0.1176
2013-01-01 05:00:00    0.1176
2013-01-01 05:30:00    0.1176
2013-01-01 06:00:00    0.1176
2013-01-01 06:30:00    0.1176
2013-01-01 07:00:00    0.1176
2013-01-01 07:30:00    0.1176
2013-01-01 08:00:00    0.1176
2013-01-01 08:30:00    0.1176
2013-01-01 09:00:00    0.1176
2013-01-01 09:30:00    0.1176
2013-01-01 10:00:00    0.1176
2013-01-01 10:30:00    0.1176
2013-01-01 11:00:00    0.1176
2013-01-01 11:30:00    0.1176
2013-01-01 12:00:00    0.1176
2013-01-01 12:30:00    0.1176
2013-01-01 13:00:00    0.1176
2013-01-01 13:30:00    0.1176
2013-01-01 14:00:00    0.1176
2013-01-01 14:30:00    0.1176
2013-01-01 15:00:00    0.1176
                        ...
2013-12-31 09:00:00    0.1176
2013-12-31 09:30:00    0.1176
2013-12-31 10:00:00    0.1176
2013-12-31 10:30:00    0.1176
2013-12-31 11:00:00    0.1176
2013-12-31 11:30:00    0.1176
2013-12-31 12:00:00    0.1176
2013-12-31 12:30:00    0.1176
2013-12-31 13:00:00    0.1176
2013-12-31 13:30:00    0.1176
2013-12-31 14:00:00    0.1176
2013-12-31 14:30:00    0.1176
2013-12-31 15:00:00    0.1176
2013-12-31 15:30:00    0.1176
2013-12-31 16:00:00    0.1176
2013-12-31 16:30:00    0.1176
2013-12-31 17:00:00    0.1176
2013-12-31 17:30:00    0.1176
2013-12-31 18:00:00    0.1176
2013-12-31 18:30:00    0.1176
2013-12-31 19:00:00    0.1176
2013-12-31 19:30:00    0.1176
2013-12-31 20:00:00    0.1176
2013-12-31 20:30:00    0.1176
2013-12-31 21:00:00    0.1176
2013-12-31 21:30:00    0.1176
2013-12-31 22:00:00    0.1176
2013-12-31 22:30:00    0.1176
2013-12-31 23:00:00    0.1176
2013-12-31 23:30:00    0.1176
Name: price, Length: 17519, dtype: float64

In [57]:
print(df_smart_meters_ToU[df_smart_meters_ToU.datetime.dt.second != 0])
print('')
print(df_smart_meters_ToU[~(df_smart_meters_ToU.datetime.dt.minute.isin([0, 30]))])

Empty DataFrame
Columns: [datetime, id, kWh]
Index: []

Empty DataFrame
Columns: [datetime, id, kWh]
Index: []

In [58]:
df_smart_meters_ToU.at[143691393, 'datetime'] = datetime(2013, 10, 29, 9, 30)
df_smart_meters_ToU.at[144709892, 'datetime'] = datetime(2013, 10, 29, 9, 30)
df_smart_meters_ToU.at[153932659, 'datetime'] = datetime(2013, 7, 5, 13, 0)
df_smart_meters_ToU.at[155953520, 'datetime'] = datetime(2013, 10, 29, 18, 30)
df_smart_meters_ToU.at[167382338, 'datetime'] = datetime(2013, 9, 20, 18, 30)

df_smart_meters_ToU[~(df_smart_meters_ToU.datetime.dt.minute.isin([0, 30]))].shape[0]

C:\Users\ABour\Anaconda3\lib\site-packages\pandas\core\frame.py:2584: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.loc[index, col] = value

0

In [60]:
## Filtering ToU df for only std prices

def datetime_2_price(datetime):
    price = df_price.loc[datetime]
    return price

df_smart_meters_ToU['price'] = df_smart_meters_ToU.datetime.apply(datetime_2_price)
df_smart_meters_ToU = df_smart_meters_ToU[df_smart_meters_ToU.price==0.1176]
df_smart_meters_ToU = df_smart_meters_ToU.drop(columns='price')
df_smart_meters_ToU

                     datetime      id    kWh
19423     2013-01-01 00:30:00     0.0  0.404
19424     2013-01-01 01:00:00     0.0  0.185
19425     2013-01-01 01:30:00     0.0  0.151
19426     2013-01-01 02:00:00     0.0  0.139
19427     2013-01-01 02:30:00     0.0  0.105
19428     2013-01-01 03:00:00     0.0  0.122
19429     2013-01-01 03:30:00     0.0  0.091
19430     2013-01-01 04:00:00     0.0  0.110
19431     2013-01-01 04:30:00     0.0  0.100
19432     2013-01-01 05:00:00     0.0  0.091
19433     2013-01-01 05:30:00     0.0  0.107
19434     2013-01-01 06:00:00     0.0  0.084
19435     2013-01-01 06:30:00     0.0  0.118
19436     2013-01-01 07:00:00     0.0  0.086
19437     2013-01-01 07:30:00     0.0  0.081
19438     2013-01-01 08:00:00     0.0  0.054
19439     2013-01-01 08:30:00     0.0  0.306
19440     2013-01-01 09:00:00     0.0  0.105
19441     2013-01-01 09:30:00     0.0  0.073
19442     2013-01-01 10:00:00     0.0  0.105
19443     2013-01-01 10:30:00     0.0  0.097
19444     2013-01-01 11:00:00     0.0  0.084
19445     2013-01-01 11:30:00     0.0  0.104
19446     2013-01-01 12:00:00     0.0  0.066
19447     2013-01-01 12:30:00     0.0  0.088
19448     2013-01-01 13:00:00     0.0  0.209
19449     2013-01-01 13:30:00     0.0  0.220
19450     2013-01-01 14:00:00     0.0  0.248
19451     2013-01-01 14:30:00     0.0  0.246
19452     2013-01-01 15:00:00     0.0  0.155
...                       ...     ...    ...
40717365  2013-12-31 11:30:00  1024.0  0.055
40717366  2013-12-31 12:00:00  1024.0  0.084
40717367  2013-12-31 12:30:00  1024.0  0.061
40717368  2013-12-31 13:00:00  1024.0  0.081
40717369  2013-12-31 13:30:00  1024.0  0.076
40717370  2013-12-31 14:00:00  1024.0  0.088
40717371  2013-12-31 14:30:00  1024.0  0.121
40717372  2013-12-31 15:00:00  1024.0  0.063
40717373  2013-12-31 15:30:00  1024.0  0.057
40717374  2013-12-31 16:00:00  1024.0  0.195
40717375  2013-12-31 16:30:00  1024.0  0.190
40717376  2013-12-31 17:00:00  1024.0  0.218
40717377  2013-12-31 17:30:00  1024.0  0.197
40717378  2013-12-31 18:00:00  1024.0  0.195
40717379  2013-12-31 18:30:00  1024.0  0.243
40717380  2013-12-31 19:00:00  1024.0  0.230
40717381  2013-12-31 19:30:00  1024.0  0.242
40717382  2013-12-31 20:00:00  1024.0  1.004
40717383  2013-12-31 20:30:00  1024.0  0.211
40717384  2013-12-31 21:00:00  1024.0  0.142
40717385  2013-12-31 21:30:00  1024.0  0.076
40717386  2013-12-31 22:00:00  1024.0  0.100
40717387  2013-12-31 22:30:00  1024.0  0.098
40717388  2013-12-31 23:00:00  1024.0  0.089
40717389  2013-12-31 23:30:00  1024.0  0.093
143691393 2013-10-29 09:30:00     NaN    NaN
144709892 2013-10-29 09:30:00     NaN    NaN
153932659 2013-07-05 13:00:00     NaN    NaN
155953520 2013-10-29 18:30:00     NaN    NaN
167382338 2013-09-20 18:30:00     NaN    NaN

[15648226 rows x 3 columns]

In [61]:
def pre_proc_ts_feature_gen(df):
    df = pp.generate_ts_features_df(df)
    df['kWh'] = df.kWh.replace('Null', None).astype(float)
    return df

df_smart_meters_std = pre_proc_ts_feature_gen(df_smart_meters_std)
df_smart_meters_ToU = pre_proc_ts_feature_gen(df_smart_meters_ToU)

In [62]:
plot_households = False

if plot_households == True:
    for _id in df_smart_meters.id.unique():
        ## Filter df for smart meter id
        df_smart_meter = df_smart_meters[df_smart_meters.id==_id]

        ## Plots
        pp.plot_SP_mean(_id, df_smart_meter)
        pp.plot_datetime_heatmap(_id, df_smart_meter)
        pp.plot_daily_peak_dist(_id, df_smart_meter)
    
## Try dropping zero values before rather than later, compare speed

<br>

### Feature Generation

<img src="img/SMAP features.png">

In [68]:
## Creating array of SMAP feature keywords

## Need to add a pre-pre-filter for night & weekend combo, five so far
## They have mean daily maximum usage as well as mean peak usage, are they not the same? 
## Need a method to filter out peak usage
## Need to add seasonal filters

SMAP_features = np.array([
    [None, None, None, 'mean'], # Mean usage
    [None, None, None, 'var'], # Variance of usage
    [None, 'DoY', 'max', 'mean'], # Mean peak usage
    [None, 'DoY', 'max', 'var'], # Variance of peak usage
    ['day', None, None, 'mean'], # Mean night usage
    ['night', None, None, 'mean'], # Mean day usage
    ['day', None, None, 'var'], # Variance of night usage
    ['weekend', None, None, 'mean'], # Mean weekday usage
    ['weekend', None, None, 'var'], # Variance of weekday usage
    [None, 'DoY', 'min', 'mean'], # Mean trough usage
    [None, 'SP', 'var', 'mean'], # Mean of half-hourly coefficients of variation
    ['not_lunch', None, None, 'mean'], # Mean lunchtime usage
    [None, None, None, 'max'], # Peak usage
    [None, None, None, 'min'], # Trough usage
    ['night', None, None, 'var'], # Variance of day usage
    ['weekend', 'DoY', 'max', 'mean'], # Mean weekday peak usage
    ['weekend', 'DoY', 'max', 'var'], # Variance of weekday peak usage
    ['weekday', None, None, 'mean'], # Mean weekend usage
    ['weekday', None, None, 'var'], # Variance of weekend usage
    [None, 'SP', 'mean', None], # Mean of half-hourly usage
    [None, 'SP', 'var', None], # Variance of half-hourly usage
])

In [69]:
def generate_household_features(df_smart_meters):
    house_dict = dict()

    for _id in df_smart_meters.id.unique():
        house_dict[_id] = dict() # Creating dictionary entry for new household id
        df_smart_meter = df_smart_meters[df_smart_meters.id==_id] # Filter df for smart meter id

        for i in range(SMAP_features.shape[0]):
            drop, time_step, time_step_feature, final_feature = SMAP_features[i]
            house_dict = fg.feature_gen(df_smart_meter, _id, house_dict, drop=drop, time_step=time_step, time_step_feature=time_step_feature, final_feature=final_feature)

    return house_dict

ToU_household_dict = generate_household_features(df_smart_meters_ToU)
std_household_dict = generate_household_features(df_smart_meters_std)

In [70]:
def household_dict_2_df(house_dict):
    df_households = pd.DataFrame(house_dict).T
    df_households['day/night'] = df_households['drop_night_combined_mean']/df_households['drop_day_combined_mean']

    df_households.index.name = 'household_id'
    return df_households

df_ToU = household_dict_2_df(ToU_household_dict)
df_std = household_dict_2_df(std_household_dict)

In [71]:
df_ToU.to_csv(f'data/ToU_ts_features_d_format.csv')
df_std.to_csv(f'data/std_ts_features_d_format.csv')